version: '3.1'
services:
 kafka0:
    image: clgriffin17/kafka-base:0.1.1
    environment:
        KAFKA_BROKER_ID: 0
        KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9080
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:9080
        KAFKA_LOG_DIRS: "/kafka/data"
        KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
        KAFKA_DELETE_TOPIC_ENABLE: "true"
        KAFKA_LOG_RETENTION_HOURS: 24
        KAFKA_LOG_CLEANUP_POLICY: "delete"
        KAFKA_SEGMENT_BYTES: 104857600
        KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
    networks:
      - graylog_zookeeper_net
    ports:
      - "9080:9080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - graylog_kafka0:/kafka/data

networks:
  graylog_zookeeper_net:
    external: true

volumes:
  graylog_kafka0:
    external: true  
